import os,sqlite3
from pathlib import Path
DB=Path(os.getenv("TAYEB_DB_PATH",str(Path(__file__).resolve().parent/"tayeb.db"))); DB.parent.mkdir(parents=True,exist_ok=True)
def connect():
 c=sqlite3.connect(DB); c.row_factory=sqlite3.Row; c.execute("PRAGMA foreign_keys=ON"); return c
def init_db():
 with connect() as c:
  c.executescript("""CREATE TABLE IF NOT EXISTS projects(id INTEGER PRIMARY KEY,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,client TEXT DEFAULT '',location TEXT DEFAULT '',contract_value REAL DEFAULT 0,start_date TEXT,end_date TEXT,status TEXT DEFAULT 'Planning',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tasks(id INTEGER PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,name TEXT NOT NULL,start_date TEXT,end_date TEXT,progress REAL DEFAULT 0);
CREATE TABLE IF NOT EXISTS boq(id INTEGER PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,code TEXT NOT NULL,description TEXT NOT NULL,unit TEXT DEFAULT 'unit',quantity REAL DEFAULT 0,unit_rate REAL DEFAULT 0,category TEXT DEFAULT 'General',UNIQUE(project_id,code));
CREATE TABLE IF NOT EXISTS resources(id INTEGER PRIMARY KEY,kind TEXT NOT NULL,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,unit TEXT DEFAULT 'unit',unit_cost REAL DEFAULT 0);
CREATE TABLE IF NOT EXISTS workers(id INTEGER PRIMARY KEY,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,role TEXT DEFAULT 'Worker',phone TEXT DEFAULT '',daily_rate REAL DEFAULT 0,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS attendance(id INTEGER PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,worker_id INTEGER NOT NULL REFERENCES workers(id),work_date TEXT NOT NULL,hours REAL DEFAULT 8,status TEXT DEFAULT 'Present',UNIQUE(project_id,worker_id,work_date));
CREATE TABLE IF NOT EXISTS equipment(id INTEGER PRIMARY KEY,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,equipment_type TEXT DEFAULT 'Machine',hourly_rate REAL DEFAULT 0,status TEXT DEFAULT 'Available');
CREATE TABLE IF NOT EXISTS equipment_logs(id INTEGER PRIMARY KEY,equipment_id INTEGER NOT NULL REFERENCES equipment(id),project_id INTEGER REFERENCES projects(id),work_date TEXT NOT NULL,hours REAL DEFAULT 0,cost REAL DEFAULT 0,notes TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS materials(id INTEGER PRIMARY KEY,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,unit TEXT DEFAULT 'unit',unit_cost REAL DEFAULT 0,stock REAL DEFAULT 0,reorder_level REAL DEFAULT 0);
CREATE TABLE IF NOT EXISTS material_moves(id INTEGER PRIMARY KEY,project_id INTEGER REFERENCES projects(id),material_id INTEGER REFERENCES materials(id),quantity REAL NOT NULL,move_type TEXT NOT NULL,reference TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS purchases(id INTEGER PRIMARY KEY,project_id INTEGER REFERENCES projects(id),supplier TEXT DEFAULT '',reference TEXT UNIQUE NOT NULL,amount REAL DEFAULT 0,status TEXT DEFAULT 'Draft',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS purchase_items(id INTEGER PRIMARY KEY,purchase_id INTEGER NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,material_id INTEGER REFERENCES materials(id),description TEXT,quantity REAL DEFAULT 0,unit_rate REAL DEFAULT 0);
CREATE TABLE IF NOT EXISTS subcontractors(id INTEGER PRIMARY KEY,project_id INTEGER REFERENCES projects(id),company TEXT NOT NULL,scope TEXT DEFAULT '',contract_value REAL DEFAULT 0,retention_percent REAL DEFAULT 5,status TEXT DEFAULT 'Active');
CREATE TABLE IF NOT EXISTS daily_reports(id INTEGER PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,report_date TEXT NOT NULL,summary TEXT DEFAULT '',progress_percent REAL DEFAULT 0,labour_count INTEGER DEFAULT 0,material_cost REAL DEFAULT 0,equipment_cost REAL DEFAULT 0,notes TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS billings(id INTEGER PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,invoice_no TEXT UNIQUE NOT NULL,gross_amount REAL DEFAULT 0,retention_percent REAL DEFAULT 5,tax_amount REAL DEFAULT 0,status TEXT DEFAULT 'Draft',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cashflow(id INTEGER PRIMARY KEY,project_id INTEGER REFERENCES projects(id),entry_date TEXT NOT NULL,direction TEXT NOT NULL,category TEXT NOT NULL,amount REAL DEFAULT 0,reference TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS cost_entries(id INTEGER PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,entry_date TEXT NOT NULL,cost_type TEXT NOT NULL,description TEXT DEFAULT '',amount REAL NOT NULL,reference TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS bim_jobs(id INTEGER PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,source_type TEXT NOT NULL,source_uri TEXT NOT NULL,job_type TEXT DEFAULT 'takeoff',status TEXT DEFAULT 'Queued',result_json TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'viewer',active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit_log(id INTEGER PRIMARY KEY,action TEXT NOT NULL,entity TEXT NOT NULL,entity_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP);""")