import os,sqlite3
from pathlib import Path
DB=Path(os.getenv("TAYEB_DB_PATH",str(Path(__file__).resolve().parent/"tayeb.db"))); DB.parent.mkdir(parents=True,exist_ok=True)
def connect():
 c=sqlite3.connect(DB); c.row_factory=sqlite3.Row; c.execute("PRAGMA foreign_keys=ON"); return c
def init_db():
 with connect() as c:
  c.executescript("""CREATE TABLE IF NOT EXISTS projects(id INTEGER PRIMARY KEY,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,client TEXT DEFAULT '',location TEXT DEFAULT '',contract_value REAL DEFAULT 0,start_date TEXT,end_date TEXT,status TEXT DEFAULT 'Planning',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tasks(id INTEGER PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,name TEXT NOT NULL,start_date TEXT,end_date TEXT,progress REAL DEFAULT 0);
CREATE TABLE IF NOT EXISTS boq(id INTEGER PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,code TEXT NOT NULL,description TEXT NOT NULL,unit TEXT DEFAULT 'unit',quantity REAL DEFAULT 0,unit_rate REAL DEFAULT 0,category TEXT DEFAULT 'General',UNIQUE(project_id,code));
CREATE TABLE IF NOT EXISTS resources(id INTEGER PRIMARY KEY,kind TEXT NOT NULL,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,unit TEXT DEFAULT 'unit',unit_cost REAL DEFAULT 0);
CREATE TABLE IF NOT EXISTS workers(id INTEGER PRIMARY KEY,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,role TEXT DEFAULT 'Worker',phone TEXT DEFAULT '',daily_rate REAL DEFAULT 0,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS attendance(id INTEGER PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,worker_id INTEGER NOT NULL REFERENCES workers(id),work_date TEXT NOT NULL,hours REAL DEFAULT 8,status TEXT DEFAULT 'Present',UNIQUE(project_id,worker_id,work_date));
CREATE TABLE IF NOT EXISTS equipment(id INTEGER PRIMARY KEY,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,equipment_type TEXT DEFAULT 'Machine',hourly_rate REAL DEFAULT 0,status TEXT DEFAULT 'Available');
CREATE TABLE IF NOT EXISTS equipment_logs(id INTEGER PRIMARY KEY,equipment_id INTEGER NOT NULL REFERENCES equipment(id),project_id INTEGER REFERENCES projects(id),work_date TEXT NOT NULL,hours REAL DEFAULT 0,cost REAL DEFAULT 0,notes TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS materials(id INTEGER PRIMARY KEY,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,unit TEXT DEFAULT 'unit',unit_cost REAL DEFAULT 0,stock REAL DEFAULT 0,reorder_level REAL DEFAULT 0);
CREATE TABLE IF NOT EXISTS material_moves(id INTEGER PRIMARY KEY,project_id INTEGER REFERENCES projects(id),material_id INTEGER REFERENCES materials(id),quantity REAL NOT NULL,move_type TEXT NOT NULL,reference TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS purchases(id INTEGER PRIMARY KEY,project_id INTEGER REFERENCES projects(id),supplier TEXT DEFAULT '',reference TEXT UNIQUE NOT NULL,amount REAL DEFAULT 0,status TEXT DEFAULT 'Draft',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS purchase_items(id INTEGER PRIMARY KEY,purchase_id INTEGER NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,material_id INTEGER REFERENCES materials(id),description TEXT,quantity REAL DEFAULT 0,unit_rate REAL DEFAULT 0);
CREATE TABLE IF NOT EXISTS subcontractors(id INTEGER PRIMARY KEY,project_id INTEGER REFERENCES projects(id),company TEXT NOT NULL,scope TEXT DEFAULT '',contract_value REAL DEFAULT 0,retention_percent REAL DEFAULT 5,status TEXT DEFAULT 'Active');
CREATE TABLE IF NOT EXISTS daily_reports(id INTEGER PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,report_date TEXT NOT NULL,summary TEXT DEFAULT '',progress_percent REAL DEFAULT 0,labour_count INTEGER DEFAULT 0,material_cost REAL DEFAULT 0,equipment_cost REAL DEFAULT 0,notes TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS billings(id INTEGER PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,invoice_no TEXT UNIQUE NOT NULL,gross_amount REAL DEFAULT 0,retention_percent REAL DEFAULT 5,tax_amount REAL DEFAULT 0,status TEXT DEFAULT 'Draft',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS cashflow(id INTEGER PRIMARY KEY,project_id INTEGER REFERENCES projects(id),entry_date TEXT NOT NULL,direction TEXT NOT NULL,category TEXT NOT NULL,amount REAL DEFAULT 0,reference TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS cost_entries(id INTEGER PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,entry_date TEXT NOT NULL,cost_type TEXT NOT NULL,description TEXT DEFAULT '',amount REAL NOT NULL,reference TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS bim_jobs(id INTEGER PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,source_type TEXT NOT NULL,source_uri TEXT NOT NULL,job_type TEXT DEFAULT 'takeoff',status TEXT DEFAULT 'Queued',result_json TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'viewer',active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payroll_periods(id INTEGER PRIMARY KEY,period_start TEXT NOT NULL,period_end TEXT NOT NULL,status TEXT DEFAULT 'Draft',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payroll_items(id INTEGER PRIMARY KEY,period_id INTEGER NOT NULL REFERENCES payroll_periods(id) ON DELETE CASCADE,worker_id INTEGER NOT NULL REFERENCES workers(id),regular_hours REAL DEFAULT 0,overtime_hours REAL DEFAULT 0,rate_per_hour REAL DEFAULT 0,gross_amount REAL DEFAULT 0,status TEXT DEFAULT 'Draft');
CREATE TABLE IF NOT EXISTS change_orders(id INTEGER PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,code TEXT NOT NULL,description TEXT NOT NULL,amount REAL DEFAULT 0,status TEXT DEFAULT 'Draft',approved_at TEXT,UNIQUE(project_id,code));
CREATE TABLE IF NOT EXISTS progress_entries(id INTEGER PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,boq_id INTEGER REFERENCES boq(id),report_date TEXT NOT NULL,quantity REAL DEFAULT 0,unit_rate REAL DEFAULT 0,amount REAL DEFAULT 0,status TEXT DEFAULT 'Draft');
CREATE TABLE IF NOT EXISTS billing_payments(id INTEGER PRIMARY KEY,billing_id INTEGER NOT NULL REFERENCES billings(id) ON DELETE CASCADE,payment_date TEXT NOT NULL,amount REAL NOT NULL,reference TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS documents(id INTEGER PRIMARY KEY,project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE,document_type TEXT NOT NULL,name TEXT NOT NULL,storage_uri TEXT NOT NULL,version INTEGER DEFAULT 1,status TEXT DEFAULT 'Active',mime_type TEXT DEFAULT '',size_bytes INTEGER DEFAULT 0,sha256 TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS issues(id INTEGER PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,title TEXT NOT NULL,description TEXT DEFAULT '',severity TEXT DEFAULT 'Medium',status TEXT DEFAULT 'Open',due_date TEXT);
CREATE TABLE IF NOT EXISTS audit_log(id INTEGER PRIMARY KEY,action TEXT NOT NULL,entity TEXT NOT NULL,entity_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS accounts(id INTEGER PRIMARY KEY,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,account_type TEXT NOT NULL,parent_id INTEGER REFERENCES accounts(id),active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS journal_entries(id INTEGER PRIMARY KEY,entry_no TEXT UNIQUE NOT NULL,entry_date TEXT NOT NULL,description TEXT DEFAULT '',project_id INTEGER REFERENCES projects(id),status TEXT DEFAULT 'Draft',posted_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS journal_lines(id INTEGER PRIMARY KEY,journal_id INTEGER NOT NULL REFERENCES journal_entries(id) ON DELETE CASCADE,account_id INTEGER NOT NULL REFERENCES accounts(id),debit REAL DEFAULT 0,credit REAL DEFAULT 0,description TEXT DEFAULT '',project_id INTEGER REFERENCES projects(id),UNIQUE(journal_id,id));
CREATE TABLE IF NOT EXISTS budgets(id INTEGER PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,code TEXT NOT NULL,description TEXT DEFAULT '',amount REAL NOT NULL DEFAULT 0,category TEXT DEFAULT 'General',UNIQUE(project_id,code));
CREATE TABLE IF NOT EXISTS fiscal_periods(id INTEGER PRIMARY KEY,code TEXT UNIQUE NOT NULL,start_date TEXT NOT NULL,end_date TEXT NOT NULL,status TEXT DEFAULT 'Open',closed_at TEXT);
CREATE INDEX IF NOT EXISTS idx_journal_lines_account ON journal_lines(account_id);
CREATE INDEX IF NOT EXISTS idx_journal_entries_project ON journal_entries(project_id);
CREATE INDEX IF NOT EXISTS idx_cost_entries_project ON cost_entries(project_id);
CREATE INDEX IF NOT EXISTS idx_billing_payments_billing ON billing_payments(billing_id);
CREATE TABLE IF NOT EXISTS supplier_invoices(id INTEGER PRIMARY KEY,project_id INTEGER REFERENCES projects(id),supplier TEXT NOT NULL,invoice_no TEXT UNIQUE NOT NULL,invoice_date TEXT NOT NULL,due_date TEXT,amount REAL NOT NULL,tax_amount REAL DEFAULT 0,status TEXT DEFAULT 'Open',purchase_id INTEGER REFERENCES purchases(id),created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS supplier_payments(id INTEGER PRIMARY KEY,supplier_invoice_id INTEGER NOT NULL REFERENCES supplier_invoices(id) ON DELETE CASCADE,payment_date TEXT NOT NULL,amount REAL NOT NULL,reference TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS payroll_allocations(id INTEGER PRIMARY KEY,payroll_item_id INTEGER NOT NULL REFERENCES payroll_items(id) ON DELETE CASCADE,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,hours REAL NOT NULL,amount REAL NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS budget_versions(id INTEGER PRIMARY KEY,project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,version_no INTEGER NOT NULL,notes TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(project_id,version_no));
CREATE TABLE IF NOT EXISTS budget_version_items(id INTEGER PRIMARY KEY,version_id INTEGER NOT NULL REFERENCES budget_versions(id) ON DELETE CASCADE,code TEXT NOT NULL,description TEXT DEFAULT '',amount REAL NOT NULL,category TEXT DEFAULT 'General');
CREATE TABLE IF NOT EXISTS journal_reversals(id INTEGER PRIMARY KEY,original_journal_id INTEGER UNIQUE NOT NULL REFERENCES journal_entries(id),reversal_journal_id INTEGER UNIQUE NOT NULL REFERENCES journal_entries(id),reason TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO accounts(code,name,account_type) VALUES ('1000','Cash','Asset'),('1100','Accounts Receivable','Asset'),('1200','Inventory','Asset'),('1300','Retention Receivable','Asset'),('1400','Input Tax Receivable','Asset'),('2000','Accounts Payable','Liability'),('2100','Payroll Payable','Liability'),('2200','Tax Payable','Liability'),('4000','Construction Revenue','Revenue'),('5000','Construction Costs','Expense'),('5100','Payroll Expense','Expense'),('5200','Materials Expense','Expense'),('5300','Equipment Expense','Expense');""")
  supplier_cols={r[1] for r in c.execute("PRAGMA table_info(supplier_invoices)").fetchall()}
  if "status" not in supplier_cols:
   c.execute("ALTER TABLE supplier_invoices ADD COLUMN status TEXT DEFAULT 'Open'")
